config/routes.rb
NgdecorSystem::Application.routes.draw do

  resources :sellers

  devise_for :users, path_prefix: 'my_user'
  resources :users

  resources :customers
  resources :imports, only: [:new,:create]
  resources :products 
  resources :categories
  resources :suppliers do
    get 'download'
  end

  root "users#index"
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base

  has_many :products

  validates :cnpj, uniqueness: true
  validates :cnpj, :name, presence: true
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  def download
    @products = Supplier.find(params[:supplier_id]).products
    respond_to do |format|
      format.xls 
    end
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render action: 'show', status: :created, location: @supplier }
      else
        format.html { render action: 'new' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :cnpj, :address, :phone)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= simple_form_for @supplier, :html => { :class => 'form-horizontal supplier_validate' } do |f| %>
  <%= f.input :name %>
  <%= f.input :cnpj %>
  <%= f.input :address %>
  <%= f.input :phone %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                suppliers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/suppliers/download.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:html="http://www.w3.org/TR/REC-html40">
<Worksheet ss:Name="Sheet1">
<Table>
<Row>
<Cell><Data ss:Type="String">ID</Data></Cell>
<Cell><Data ss:Type="String">Name</Data></Cell>
<Cell><Data ss:Type="String">Markup</Data></Cell>
<Cell><Data ss:Type="String">Price</Data></Cell>
</Row>
<% @products.each do |product| %>
  <Row>
  <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
  <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
  <Cell><Data ss:Type="String"><%= product.markup %></Data></Cell>
  <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
  </Row>
<% end %>
</Table>
</Worksheet>
</Workbook>

app/views/suppliers/edit.html.erb
<%- model_class = Supplier -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/suppliers/index.html.erb
<%- model_class = Supplier -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cnpj) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= link_to supplier.id, supplier_path(supplier) %></td>
        <td><%= supplier.name %></td>
        <td><%= supplier.cnpj %></td>
        <td><%= supplier.address %></td>
        <td><%= supplier.phone %></td>
        <td><%=l supplier.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_supplier_path(supplier), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      supplier_path(supplier),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <%= link_to t("download"), supplier_download_path(supplier.id,format: :xls), class: 'btn btn-mini btn-info' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_supplier_path,
            :class => 'btn btn-primary' %>

app/views/suppliers/new.html.erb
<%- model_class = Supplier -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/suppliers/show.html.erb
<%- model_class = Supplier -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @supplier.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cnpj) %>:</strong></dt>
  <dd><%= @supplier.cnpj %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @supplier.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @supplier.phone %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              suppliers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_supplier_path(@supplier), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              supplier_path(@supplier),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>